print("Hello World!")
print("Hello Again")
print("I like typing this..Lies")
print("This is fun. ... Lies")
print("why you make me do this")
print("yes I get you can print on new lines")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')